name: "ezEDR"

on: [push, pull_request]

jobs:
  test-postgres:
    name: Test ezedr-postgres
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: cd ./ezedr-postgres && npm run test:e2e
