name: Core

on:
  push:
    paths:
      - "ezedr-core/**"
  pull_request:
    paths:
      - "ezedr-core/**"

jobs:

  test:
    name: Test ezedr-core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: cd ./ezedr-core && npm run check && npm run test
