name: Postgres Repository 

on:
  push:
    paths:
      - "ezedr-core/**"
      - "ezedr-postgres/**"
  pull_request:
    paths:
      - "ezedr-core/**"
      - "ezedr-postgres/**"

jobs:

  test:
    name: Test ezedr-postgres
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: cd ./ezedr-postgres && npm run check && npm run test:e2e
