name: Server

on:
  push:
    paths:
      - "ezedr-core/**"
      - "ezedr-server/**"
  pull_request:
    paths:
      - "ezedr-core/**"
      - "ezedr-server/**"

jobs:

  test:
    name: Test ezedr-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: cd ./ezedr-server && npm run check && npm run test
